app:
  forecast:
    years: ${FORECAST_YEARS}
spring:
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: ${DATABASE_SCHEMA}
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver